__title__ = "symbols"
__description__ = "A library for cryptocurrency ticker symbols manipulation."
__url__ = "https://github.com/zatura/symbols"
__author_url__ = "https://zatura.me"
__version__ = "0.6.0"
__build__ = 0x000600
__author__ = "Matheus Tura"
__license__ = "GPL-3.0"
__copyright__ = "Copyright Matheus Tura"
